//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.ReservationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfCar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfCar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Car[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsoleApp1.ReservationService.Car[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        private int RequiredDriverLicenceExpField;
        
        private int RequiredAgeField;
        
        private int KmInfoField;
        
        private bool HasAirbagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BaggageCapacityField;
        
        private decimal DailyCostField;
        
        private bool isActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Brand BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Company CompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RequiredDriverLicenceExp {
            get {
                return this.RequiredDriverLicenceExpField;
            }
            set {
                if ((this.RequiredDriverLicenceExpField.Equals(value) != true)) {
                    this.RequiredDriverLicenceExpField = value;
                    this.RaisePropertyChanged("RequiredDriverLicenceExp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int RequiredAge {
            get {
                return this.RequiredAgeField;
            }
            set {
                if ((this.RequiredAgeField.Equals(value) != true)) {
                    this.RequiredAgeField = value;
                    this.RaisePropertyChanged("RequiredAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int KmInfo {
            get {
                return this.KmInfoField;
            }
            set {
                if ((this.KmInfoField.Equals(value) != true)) {
                    this.KmInfoField = value;
                    this.RaisePropertyChanged("KmInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public bool HasAirbag {
            get {
                return this.HasAirbagField;
            }
            set {
                if ((this.HasAirbagField.Equals(value) != true)) {
                    this.HasAirbagField = value;
                    this.RaisePropertyChanged("HasAirbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string BaggageCapacity {
            get {
                return this.BaggageCapacityField;
            }
            set {
                if ((object.ReferenceEquals(this.BaggageCapacityField, value) != true)) {
                    this.BaggageCapacityField = value;
                    this.RaisePropertyChanged("BaggageCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public decimal DailyCost {
            get {
                return this.DailyCostField;
            }
            set {
                if ((this.DailyCostField.Equals(value) != true)) {
                    this.DailyCostField = value;
                    this.RaisePropertyChanged("DailyCost");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool isActive {
            get {
                return this.isActiveField;
            }
            set {
                if ((this.isActiveField.Equals(value) != true)) {
                    this.isActiveField = value;
                    this.RaisePropertyChanged("isActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public ConsoleApp1.ReservationService.Brand Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public ConsoleApp1.ReservationService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Brand", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Brand : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BrandIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BrandID {
            get {
                return this.BrandIDField;
            }
            set {
                if ((this.BrandIDField.Equals(value) != true)) {
                    this.BrandIDField = value;
                    this.RaisePropertyChanged("BrandID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        private int CarCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScoreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CarCount {
            get {
                return this.CarCountField;
            }
            set {
                if ((this.CarCountField.Equals(value) != true)) {
                    this.CarCountField = value;
                    this.RaisePropertyChanged("CarCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Score {
            get {
                return this.ScoreField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoreField, value) != true)) {
                    this.ScoreField = value;
                    this.RaisePropertyChanged("Score");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfReservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResponseOfReservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool isSuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Reservation[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool isSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                if ((this.isSuccessField.Equals(value) != true)) {
                    this.isSuccessField = value;
                    this.RaisePropertyChanged("isSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsoleApp1.ReservationService.Reservation[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Reservation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ReservationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.User UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Company CompanyField;
        
        private System.DateTime StartingDateField;
        
        private System.DateTime EndDateField;
        
        private System.DateTime ReservationMadeAtField;
        
        private int ReservationStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((this.ReservationIDField.Equals(value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public ConsoleApp1.ReservationService.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public ConsoleApp1.ReservationService.User User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ConsoleApp1.ReservationService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime StartingDate {
            get {
                return this.StartingDateField;
            }
            set {
                if ((this.StartingDateField.Equals(value) != true)) {
                    this.StartingDateField = value;
                    this.RaisePropertyChanged("StartingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime ReservationMadeAt {
            get {
                return this.ReservationMadeAtField;
            }
            set {
                if ((this.ReservationMadeAtField.Equals(value) != true)) {
                    this.ReservationMadeAtField = value;
                    this.RaisePropertyChanged("ReservationMadeAt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int ReservationState {
            get {
                return this.ReservationStateField;
            }
            set {
                if ((this.ReservationStateField.Equals(value) != true)) {
                    this.ReservationStateField = value;
                    this.RaisePropertyChanged("ReservationState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Person PersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Role RoleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ConsoleApp1.ReservationService.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public ConsoleApp1.ReservationService.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PersonIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private System.DateTime DriverLicenseDateField;
        
        private System.DateTime BirthdayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.ReservationService.Company CompanyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int PersonID {
            get {
                return this.PersonIDField;
            }
            set {
                if ((this.PersonIDField.Equals(value) != true)) {
                    this.PersonIDField = value;
                    this.RaisePropertyChanged("PersonID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime DriverLicenseDate {
            get {
                return this.DriverLicenseDateField;
            }
            set {
                if ((this.DriverLicenseDateField.Equals(value) != true)) {
                    this.DriverLicenseDateField = value;
                    this.RaisePropertyChanged("DriverLicenseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.DateTime Birthday {
            get {
                return this.BirthdayField;
            }
            set {
                if ((this.BirthdayField.Equals(value) != true)) {
                    this.BirthdayField = value;
                    this.RaisePropertyChanged("Birthday");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public ConsoleApp1.ReservationService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationService.ReservationServiceSoap")]
    public interface ReservationServiceSoap {
        
        // CODEGEN: http://tempuri.org/ ad alanındaki FetchAvailableCarsForResvResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAvailableCarsForResv", ReplyAction="*")]
        ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse FetchAvailableCarsForResv(ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAvailableCarsForResv", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse> FetchAvailableCarsForResvAsync(ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki FetchAllByIdResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAllById", ReplyAction="*")]
        ConsoleApp1.ReservationService.FetchAllByIdResponse FetchAllById(ConsoleApp1.ReservationService.FetchAllByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FetchAllById", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAllByIdResponse> FetchAllByIdAsync(ConsoleApp1.ReservationService.FetchAllByIdRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki MakeReservationResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeReservation", ReplyAction="*")]
        ConsoleApp1.ReservationService.MakeReservationResponse MakeReservation(ConsoleApp1.ReservationService.MakeReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MakeReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.MakeReservationResponse> MakeReservationAsync(ConsoleApp1.ReservationService.MakeReservationRequest request);
        
        // CODEGEN: http://tempuri.org/ ad alanındaki CancelReservationResult öğe adı sıfırlanabilir olarak işaretlenmediğinden, ileti sözleşmesi oluşturuluyor
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        ConsoleApp1.ReservationService.CancelReservationResponse CancelReservation(ConsoleApp1.ReservationService.CancelReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.CancelReservationResponse> CancelReservationAsync(ConsoleApp1.ReservationService.CancelReservationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAvailableCarsForResvRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAvailableCarsForResv", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequestBody Body;
        
        public FetchAvailableCarsForResvRequest() {
        }
        
        public FetchAvailableCarsForResvRequest(ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAvailableCarsForResvRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime startingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime endDate;
        
        public FetchAvailableCarsForResvRequestBody() {
        }
        
        public FetchAvailableCarsForResvRequestBody(int UserID, System.DateTime startingDate, System.DateTime endDate) {
            this.UserID = UserID;
            this.startingDate = startingDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAvailableCarsForResvResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAvailableCarsForResvResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponseBody Body;
        
        public FetchAvailableCarsForResvResponse() {
        }
        
        public FetchAvailableCarsForResvResponse(ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAvailableCarsForResvResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp1.ReservationService.ResponseOfCar FetchAvailableCarsForResvResult;
        
        public FetchAvailableCarsForResvResponseBody() {
        }
        
        public FetchAvailableCarsForResvResponseBody(ConsoleApp1.ReservationService.ResponseOfCar FetchAvailableCarsForResvResult) {
            this.FetchAvailableCarsForResvResult = FetchAvailableCarsForResvResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAllByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAllById", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.FetchAllByIdRequestBody Body;
        
        public FetchAllByIdRequest() {
        }
        
        public FetchAllByIdRequest(ConsoleApp1.ReservationService.FetchAllByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAllByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        public FetchAllByIdRequestBody() {
        }
        
        public FetchAllByIdRequestBody(int UserID) {
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FetchAllByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FetchAllByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.FetchAllByIdResponseBody Body;
        
        public FetchAllByIdResponse() {
        }
        
        public FetchAllByIdResponse(ConsoleApp1.ReservationService.FetchAllByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FetchAllByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp1.ReservationService.ResponseOfReservation FetchAllByIdResult;
        
        public FetchAllByIdResponseBody() {
        }
        
        public FetchAllByIdResponseBody(ConsoleApp1.ReservationService.ResponseOfReservation FetchAllByIdResult) {
            this.FetchAllByIdResult = FetchAllByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeReservation", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.MakeReservationRequestBody Body;
        
        public MakeReservationRequest() {
        }
        
        public MakeReservationRequest(ConsoleApp1.ReservationService.MakeReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CarID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime startingDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime endDate;
        
        public MakeReservationRequestBody() {
        }
        
        public MakeReservationRequestBody(int CarID, int UserID, System.DateTime startingDate, System.DateTime endDate) {
            this.CarID = CarID;
            this.UserID = UserID;
            this.startingDate = startingDate;
            this.endDate = endDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MakeReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MakeReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.MakeReservationResponseBody Body;
        
        public MakeReservationResponse() {
        }
        
        public MakeReservationResponse(ConsoleApp1.ReservationService.MakeReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MakeReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp1.ReservationService.ResponseOfReservation MakeReservationResult;
        
        public MakeReservationResponseBody() {
        }
        
        public MakeReservationResponseBody(ConsoleApp1.ReservationService.ResponseOfReservation MakeReservationResult) {
            this.MakeReservationResult = MakeReservationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReservation", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.CancelReservationRequestBody Body;
        
        public CancelReservationRequest() {
        }
        
        public CancelReservationRequest(ConsoleApp1.ReservationService.CancelReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ReservationID;
        
        public CancelReservationRequestBody() {
        }
        
        public CancelReservationRequestBody(int ReservationID) {
            this.ReservationID = ReservationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp1.ReservationService.CancelReservationResponseBody Body;
        
        public CancelReservationResponse() {
        }
        
        public CancelReservationResponse(ConsoleApp1.ReservationService.CancelReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CancelReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApp1.ReservationService.ResponseOfReservation CancelReservationResult;
        
        public CancelReservationResponseBody() {
        }
        
        public CancelReservationResponseBody(ConsoleApp1.ReservationService.ResponseOfReservation CancelReservationResult) {
            this.CancelReservationResult = CancelReservationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReservationServiceSoapChannel : ConsoleApp1.ReservationService.ReservationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApp1.ReservationService.ReservationServiceSoap>, ConsoleApp1.ReservationService.ReservationServiceSoap {
        
        public ReservationServiceSoapClient() {
        }
        
        public ReservationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse ConsoleApp1.ReservationService.ReservationServiceSoap.FetchAvailableCarsForResv(ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest request) {
            return base.Channel.FetchAvailableCarsForResv(request);
        }
        
        public ConsoleApp1.ReservationService.ResponseOfCar FetchAvailableCarsForResv(int UserID, System.DateTime startingDate, System.DateTime endDate) {
            ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest inValue = new ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest();
            inValue.Body = new ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.startingDate = startingDate;
            inValue.Body.endDate = endDate;
            ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse retVal = ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).FetchAvailableCarsForResv(inValue);
            return retVal.Body.FetchAvailableCarsForResvResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse> ConsoleApp1.ReservationService.ReservationServiceSoap.FetchAvailableCarsForResvAsync(ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest request) {
            return base.Channel.FetchAvailableCarsForResvAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAvailableCarsForResvResponse> FetchAvailableCarsForResvAsync(int UserID, System.DateTime startingDate, System.DateTime endDate) {
            ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest inValue = new ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequest();
            inValue.Body = new ConsoleApp1.ReservationService.FetchAvailableCarsForResvRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.startingDate = startingDate;
            inValue.Body.endDate = endDate;
            return ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).FetchAvailableCarsForResvAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ReservationService.FetchAllByIdResponse ConsoleApp1.ReservationService.ReservationServiceSoap.FetchAllById(ConsoleApp1.ReservationService.FetchAllByIdRequest request) {
            return base.Channel.FetchAllById(request);
        }
        
        public ConsoleApp1.ReservationService.ResponseOfReservation FetchAllById(int UserID) {
            ConsoleApp1.ReservationService.FetchAllByIdRequest inValue = new ConsoleApp1.ReservationService.FetchAllByIdRequest();
            inValue.Body = new ConsoleApp1.ReservationService.FetchAllByIdRequestBody();
            inValue.Body.UserID = UserID;
            ConsoleApp1.ReservationService.FetchAllByIdResponse retVal = ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).FetchAllById(inValue);
            return retVal.Body.FetchAllByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAllByIdResponse> ConsoleApp1.ReservationService.ReservationServiceSoap.FetchAllByIdAsync(ConsoleApp1.ReservationService.FetchAllByIdRequest request) {
            return base.Channel.FetchAllByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ReservationService.FetchAllByIdResponse> FetchAllByIdAsync(int UserID) {
            ConsoleApp1.ReservationService.FetchAllByIdRequest inValue = new ConsoleApp1.ReservationService.FetchAllByIdRequest();
            inValue.Body = new ConsoleApp1.ReservationService.FetchAllByIdRequestBody();
            inValue.Body.UserID = UserID;
            return ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).FetchAllByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ReservationService.MakeReservationResponse ConsoleApp1.ReservationService.ReservationServiceSoap.MakeReservation(ConsoleApp1.ReservationService.MakeReservationRequest request) {
            return base.Channel.MakeReservation(request);
        }
        
        public ConsoleApp1.ReservationService.ResponseOfReservation MakeReservation(int CarID, int UserID, System.DateTime startingDate, System.DateTime endDate) {
            ConsoleApp1.ReservationService.MakeReservationRequest inValue = new ConsoleApp1.ReservationService.MakeReservationRequest();
            inValue.Body = new ConsoleApp1.ReservationService.MakeReservationRequestBody();
            inValue.Body.CarID = CarID;
            inValue.Body.UserID = UserID;
            inValue.Body.startingDate = startingDate;
            inValue.Body.endDate = endDate;
            ConsoleApp1.ReservationService.MakeReservationResponse retVal = ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).MakeReservation(inValue);
            return retVal.Body.MakeReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.MakeReservationResponse> ConsoleApp1.ReservationService.ReservationServiceSoap.MakeReservationAsync(ConsoleApp1.ReservationService.MakeReservationRequest request) {
            return base.Channel.MakeReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ReservationService.MakeReservationResponse> MakeReservationAsync(int CarID, int UserID, System.DateTime startingDate, System.DateTime endDate) {
            ConsoleApp1.ReservationService.MakeReservationRequest inValue = new ConsoleApp1.ReservationService.MakeReservationRequest();
            inValue.Body = new ConsoleApp1.ReservationService.MakeReservationRequestBody();
            inValue.Body.CarID = CarID;
            inValue.Body.UserID = UserID;
            inValue.Body.startingDate = startingDate;
            inValue.Body.endDate = endDate;
            return ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).MakeReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp1.ReservationService.CancelReservationResponse ConsoleApp1.ReservationService.ReservationServiceSoap.CancelReservation(ConsoleApp1.ReservationService.CancelReservationRequest request) {
            return base.Channel.CancelReservation(request);
        }
        
        public ConsoleApp1.ReservationService.ResponseOfReservation CancelReservation(int ReservationID) {
            ConsoleApp1.ReservationService.CancelReservationRequest inValue = new ConsoleApp1.ReservationService.CancelReservationRequest();
            inValue.Body = new ConsoleApp1.ReservationService.CancelReservationRequestBody();
            inValue.Body.ReservationID = ReservationID;
            ConsoleApp1.ReservationService.CancelReservationResponse retVal = ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).CancelReservation(inValue);
            return retVal.Body.CancelReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp1.ReservationService.CancelReservationResponse> ConsoleApp1.ReservationService.ReservationServiceSoap.CancelReservationAsync(ConsoleApp1.ReservationService.CancelReservationRequest request) {
            return base.Channel.CancelReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.ReservationService.CancelReservationResponse> CancelReservationAsync(int ReservationID) {
            ConsoleApp1.ReservationService.CancelReservationRequest inValue = new ConsoleApp1.ReservationService.CancelReservationRequest();
            inValue.Body = new ConsoleApp1.ReservationService.CancelReservationRequestBody();
            inValue.Body.ReservationID = ReservationID;
            return ((ConsoleApp1.ReservationService.ReservationServiceSoap)(this)).CancelReservationAsync(inValue);
        }
    }
}
